# Dependencies
# markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Up&Up
tagline:          ''
description:      'Best practices, code snippets, and other wisdom nuggets'
url:              http://best_practices.mergeweb.net
baseurl:          /

author:
  name:           'Up&Up'
  url:            https://twitter.com/merge

paginate:         5

# Custom vars
version:          .1

github:
  repo:           https://github.com/mergeweb/best_practices

theme: jekyll-theme-cayman