# Dependencies
markdown:         kramdown
highlighter:      pygments


# Permalinks
permalink:        pretty

# Setup
title:            Up&Up
tagline:          ''
description:      'Best practices, code snippets, and other wisdom nuggets'
url:              http://mergeweb.github.io/best_practices/
baseurl:          /best_practices/

author:
  name:           'Up&Up'
  url:            https://twitter.com/upandupagency

paginate:         5

# Custom vars
version:          .1

github:
  repo:           https://github.com/mergeweb/best_practices

theme: jekyll-theme-cayman